version: '3.7'

services:

  angular-tut:
    container_name: angular-tut
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
